---
title: "GMSE_output_analysis"
author: "Imke Tomsin"
date: "2024-04-11"
output: html_document
---
# Load data to be analysed 
```{r}
sim_1 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/Simulation1_100it_15startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
library(dplyr)
new_rows <- sim_1 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 15) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_1 <- bind_rows(sim_1, new_rows)


sim_2 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/Simulation2_1000it_15startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_2 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 15) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_2 <- bind_rows(sim_2, new_rows)


sim_3 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/Simulation3_100it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_3 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_3 <- bind_rows(sim_3, new_rows)


sim_4 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/Simulation4_1000it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_4 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_4 <- bind_rows(sim_4, new_rows)


sim_5 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/Simulation5_100it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_5 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_5 <- bind_rows(sim_5, new_rows)


sim_6 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/simulation6_100it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_6 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_6 <- bind_rows(sim_6, new_rows)

sim_7 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/simulation7_100it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_7 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_7 <- bind_rows(sim_7, new_rows)

sim_8 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/simulation8_4x1_4x2_2x3_100it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_8 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_8 <- bind_rows(sim_8, new_rows)

sim_9 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/simulation9_100it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_9 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_9 <- bind_rows(sim_9, new_rows)

sim_10 <- read.csv("C:/Users/imket/Documents/GitHub/European_hamster_GMSE/Output/simulation10_100it_250startN.csv", header=TRUE,sep=",")
#Add starting population size (time = 0, N = 15 or 250) to each iteration
new_rows <- sim_10 %>%
  group_by(rep) %>%
  slice(1) %>%
  mutate(Time = 0, Pop_size = 250) %>%
  select(rep, Time, Pop_size)
# Bind the new rows to the original data
sim_10 <- bind_rows(sim_10, new_rows)



```

# Plot all simulations on one graph + their mean

```{r}
library(ggplot2)
library(gridExtra)

generate_plot <- function(data, plot_title) {
  ggplot(data, aes(x = Time, y = Pop_size, group = rep)) +
    theme_minimal()+
    geom_line(color = "lightgrey") + #plot all iterations as grey lines 
    stat_summary(fun = "mean", geom = "line", aes(group = 1), color = "black", linewidth = 0.82) + #plot the mean as a dark/black line
    labs(x = "Time", y = "Population Size", title = plot_title)+ #add labels and titles
    scale_x_continuous(expand = c(0, 0), limits = c(0, 60))+  # Ensure x-axis starts at 0 and stops at 60
    scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) # Same for y-axis
} 

plot_1<-generate_plot(sim_1, "Scenario 1")
plot_2<-generate_plot(sim_2, "Scenario 2")
plot_3<-generate_plot(sim_3, "Scenario 3")
plot_4<-generate_plot(sim_4, "Scenario 4")
plot_5<-generate_plot(sim_5, "Scenario 5")
plot_6<-generate_plot(sim_6, "Scenario 6")
plot_7<-generate_plot(sim_7, "Scenario 7")
plot_8<-generate_plot(sim_8, "Scenario 8")
plot_9<-generate_plot(sim_9, "Scenario 9")
plot_10<-generate_plot(sim_10, "Scenario 10")



# print(plot_1)

grid.arrange(plot_1, plot_2, nrow = 1)
grid.arrange(plot_3, plot_4, nrow = 1)
grid.arrange(plot_1, plot_2, plot_3, plot_4, nrow = 2)


grid.arrange(plot_5, plot_6, plot_7, nrow = 2)
grid.arrange(plot_8, plot_9, plot_10, nrow = 2)

```


# Show mean for population dynamics for each of the starting population sizes 
```{r}
# Calculate the mean population size for each analysis 
mean_pop1 <- aggregate(Pop_size ~ Time, sim_1, mean)
mean_pop2 <- aggregate(Pop_size ~ Time, sim_2, mean)
mean_pop3 <- aggregate(Pop_size ~ Time, sim_3, mean)
mean_pop4 <- aggregate(Pop_size ~ Time, sim_4, mean)
mean_pop5 <- aggregate(Pop_size ~ Time, sim_5, mean)
mean_pop6 <- aggregate(Pop_size ~ Time, sim_6, mean)

mean_pop7 <- aggregate(Pop_size ~ Time, sim_7, mean)
mean_pop8 <- aggregate(Pop_size ~ Time, sim_8, mean)
mean_pop9 <- aggregate(Pop_size ~ Time, sim_9, mean)
mean_pop10 <- aggregate(Pop_size ~ Time, sim_10, mean)

# Calculate the standard deviation
sd_pop1 <- aggregate(Pop_size ~ Time, sim_1, sd)
sd_pop2 <- aggregate(Pop_size ~ Time, sim_2, sd)
sd_pop3 <- aggregate(Pop_size ~ Time, sim_3, sd)
sd_pop4 <- aggregate(Pop_size ~ Time, sim_4, sd)
sd_pop5 <- aggregate(Pop_size ~ Time, sim_5, sd)
sd_pop6 <- aggregate(Pop_size ~ Time, sim_6, sd)
sd_pop7 <- aggregate(Pop_size ~ Time, sim_7, sd)
sd_pop8 <- aggregate(Pop_size ~ Time, sim_8, sd)
sd_pop9 <- aggregate(Pop_size ~ Time, sim_9, sd)
sd_pop10 <- aggregate(Pop_size ~ Time, sim_10, sd)

# Combine the mean population sizes from all analyses into a single data frame
combined_mean_pop <- rbind(mean_pop5, mean_pop6)
combined_mean_pop$Analysis <- rep(c("Scenario 5", "Scenario 6"), each = nrow(mean_pop5))

# Plot the combined mean population sizes
ggplot(combined_mean_pop, aes(x = Time, y = Pop_size, color = Analysis)) +
  geom_line() +
  theme_minimal()+
  labs(x = "Time", y = "Mean Population Size")+
  scale_x_continuous(expand = c(0, 0), limits = c(0, 60))+  # Ensure x-axis starts at 0 and stops at 60
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) # Same for y-axis



# Combine the mean population sizes from all analyses into a single data frame
combined_mean_pop2 <- rbind(mean_pop1, mean_pop2, mean_pop3, mean_pop4)
combined_mean_pop2$Analysis <- rep(c("Scenario 1", "Scenario 2","Scenario 3","Scenario 4"), each = nrow(mean_pop1))

# Plot the combined mean population sizes
custom_colors <- c( "#D0832E", "#EBD657", "#2FABAB", "#92C37F")  # Adjust colors as needed

ggplot(combined_mean_pop2, aes(x = Time, y = Pop_size, color = Analysis)) +
  geom_line(linewidth=0.7) +
  theme_minimal()+
  labs(x = "Time", y = "Mean Population Size")+
  scale_x_continuous(expand = c(0, 0), limits = c(0, 60))+  # Ensure x-axis starts at 0 and stops at 60
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA))+ # Same for y-axis
  scale_color_manual(values = custom_colors) +  # Apply custom colors
  theme(
    axis.title = element_text(size = 14),  # Increase size of axis titles
    axis.text = element_text(size = 12),   # Increase size of axis labels
    legend.title = element_text(size = 14), # Increase size of legend titles
    legend.text = element_text(size = 12)  # Increase size of legend text
  )


```

```{r}
# Calculation of coefficient of variation
# Combine mean and SD for sim_1
combined_pop1 <- merge(mean_pop1, sd_pop1, by = "Time", suffixes = c("_mean", "_sd"))
# Repeat for other simulations
combined_pop2 <- merge(mean_pop2, sd_pop2, by = "Time", suffixes = c("_mean", "_sd"))
combined_pop3 <- merge(mean_pop3, sd_pop3, by = "Time", suffixes = c("_mean", "_sd"))
combined_pop4 <- merge(mean_pop4, sd_pop4, by = "Time", suffixes = c("_mean", "_sd"))
# Calculate CV for sim_1
combined_pop1$CV <- (combined_pop1$Pop_size_sd / combined_pop1$Pop_size_mean) * 100
# Repeat for other simulations
combined_pop2$CV <- (combined_pop2$Pop_size_sd / combined_pop2$Pop_size_mean) * 100
combined_pop3$CV <- (combined_pop3$Pop_size_sd / combined_pop3$Pop_size_mean) * 100
combined_pop4$CV <- (combined_pop4$Pop_size_sd / combined_pop4$Pop_size_mean) * 100


# Histogram to show distribution of  final pop sizes

final_populations <- sim_4 %>% filter(Time == 60) %>% pull(Pop_size)

# Plot the histogram
ggplot(data.frame(FinalPopulation = final_populations), aes(x = FinalPopulation)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  labs(title = "Histogram of Final Population Sizes",
       x = "Final Population Size",
       y = "Frequency") +
  theme_minimal()

# Growth rate 

#Could be interesting to calculate??

```


# Calculate the probability of extinction
```{r}
# Determine the number of repetitions
reps <- max(sim_8$rep)

# Initialize a counter for extinction events
extinction_count <- 0

# Loop through each repetition
for (i in 1:reps) {
  # Subset data for the current repetition
  rep_data <- subset(sim_8, rep == i)
  
  # Check if the population size ever reaches zero
  if (any(rep_data$Pop_size == 0)) {
    extinction_count <- extinction_count + 1
  }
}

# Calculate the probability of extinction
probability_extinction <- extinction_count / reps

# Print the result
print(paste("Probability of extinction:", probability_extinction))


```



